### ISSUE TITLE
Broken with new Google Play Music layout

### ISSUE THREAD

**Issue by outadoc** [fuzeman/GoogleMusicScrobbler#30] opened 2015-05-14 19:23 UTC
The new Material version of Google Play Music is broken when using this extension. Not only does the extension not work, but when it is enabled, no music at all will show up in the library.

**Comment by fuzeman** [comment] 2015-05-16 02:34
Will start working on a fix for this today.

**Comment by PerfectSlayer** [comment] 2015-05-16 09:05
Thanks you! :+1:

**Comment by fuzeman** [comment] 2015-05-16 09:05
Just released **[v0.8.0-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.0-beta)**, this update should fix all the Google Music compatibility issues.

Let me know if you find any bugs :smile:

**Comment by PerfectSlayer** [comment] 2015-05-16 09:12
Works for me!
I will make some longer tries in the day :wink:

**Comment by PerfectSlayer** [comment] 2015-05-16 10:49
The plugin does'nt seem to find track and progress if the Google music tab is not selected?
So no scrobble if I browse normally on the Web… :sob:

**Comment by fuzeman** [comment] 2015-05-17 02:50
@PerfectSlayer I've figured out a solution to that issue, should have a fix released later today.

**Comment by fuzeman** [comment] 2015-05-17 06:49
Just released **[v0.8.2-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.2-beta)** with the fix, let me know if you find any other issues.

**Comment by PerfectSlayer** [comment] 2015-05-17 08:30
@fuzeman Thanks! I give it a try today :wink: 
(The background detection seems to work on my first tries)

Another question: What the status icon is supposed to display? Only a red square? (I could not find any screenshot on AMO about the feature)
![scrobble](https://cloud.githubusercontent.com/assets/1766222/7669647/a9afdd3e-fc7f-11e4-9785-a08f1ad76774.PNG)

**Comment by fuzeman** [comment] 2015-05-17 23:58
@PerfectSlayer The status icon is currently just to show the addon has been loaded correctly.

Displaying your currently playing song (or last song scrobbled) might be more helpful to see if the addon is actually scrobbling your music correctly. *(might include this in the next update)*

**Comment by lucasoutloud** [comment] 2015-05-18 02:24
@fuzeman I installed the 0.8.2 beta and find that the extension fails to scrobble regardless of whether the tab is focused. This is in Firefox 38 on Linux.

**Comment by fuzeman** [comment] 2015-05-18 05:22
@lucasoutloud could you copy the debug messages from the addon by:
 - Opening the browser console (```Menu -> Developer -> Browser Console``` or ```Ctrl + Shift + J```)
 - Refresh/Open Google Music and start playing a song
 - Messages should come up with the prefix ```GMS``` or ```LFM```
 - Copy the messages into here, or take a screenshot

**Note:** you can disable the "Net", "CSS", etc.. logging (by clicking on the buttons) in the browser console to find the messages easily.

-----------------------------------------------------------

You should see something like:

![](http://i.imgur.com/HIt7BQY.png)

**Comment by PerfectSlayer** [comment] 2015-05-18 06:55
@fuzeman OK thanks. I'm new to the add-on so I didn't know the expected behavior. 

The add-on works fine yesterday for me on Firefox 38.0.1 under Windows 7.

**Comment by Marsup** [comment] 2015-05-18 09:48
FWIW it stopped working with 0.8.2 when electrolysis is enabled, it was working fine with 0.8.0 (with the focus problem), no icon, nothing in the logs either.

**Comment by fuzeman** [comment] 2015-05-18 12:15
Will look into the issue with electrolysis, there was some fairly big changes in 0.8.2 which could of caused this.

**Comment by lucasoutloud** [comment] 2015-05-18 21:09
@fuzeman "GMS-PS" Object { Xy: false, tw: Array[2], Wp: Object, jza: Object, P0: null, YB: Object, Td: Object, DK: Object, tc: Object, Ux: null, 2 more… } Array [ Object, true, false, Object ] page.js:57:16
"GMS-PS" Object { Xy: false, tw: Array[2], Wp: Object, jza: Object, P0: null, YB: Object, Td: Object, DK: Object, tc: Object, Ux: null, 2 more… } Array [ Object, false, false, Object ]
is what I'm getting with the GMS prefix, nothing with LMS.

**Comment by fuzeman** [comment] 2015-05-19 03:57
Figured out a solution to the Electrolysis compatibility issue, just need to clean a few things up for release *(hopefully will have it released later today)*.

@lucasoutloud it appears to be receiving the play events then, I'll do some further testing to see what could be causing this.

**Comment by fuzeman** [comment] 2015-05-19 08:07
@lucasoutloud Looks like you need the option "extensions.sdk.console.logLevel" set to "debug" (in ```about:config```) to see all the messages logged from the addon, that would explain why you are only seeing the "GMS-PS" message.

------------------------------------------------

I've just released [v0.8.3-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.3-beta), this fixes a compatibility issue with electrolysis.

**Comment by Marsup** [comment] 2015-05-19 08:09
No xpi ?

**Comment by fuzeman** [comment] 2015-05-19 08:10
Yeah, forgot about the xpi. Will be uploaded shortly.

**Comment by fuzeman** [comment] 2015-05-19 08:13
XPI for 0.8.3-beta is available now.

**Comment by Marsup** [comment] 2015-05-19 08:24
Fix confirmed, both for e10s and focus. I had to restart the browser though, weird for a restartless extension.

**Comment by lucasoutloud** [comment] 2015-05-19 17:53
@fuzeman For some reason, it's saying that the track lengths are not valid integers. 
"GMS-PS" Object { Xy: false, tw: Array[2], Wp: Object, jza: Object, P0: null, YB: Object, Td: Object, DK: Object, tc: Object, Ux: null, 2 more… } Array [ Object, false, false, Object ] page.js:57:16
POST 
XHR 
https://ws.audioscrobbler.com/2.0/ [HTTP/1.1 200 OK 999ms]
"GMS.Scrobbler.setPlaying" Object { track: "Violet Stars Happy Hunting!!!", artist: "Janelle Monae", album: "Metropolis The Chase Suite", albumArtist: "", duration: 193.617, trackNumber: 2 } sandbox.js:305
"GMS.Scrobbler.setPlayingState" true sandbox.js:305
"LFM.call - method: "track.updateNowPlaying", parameters:" Object { sk: "4e8aab830a0adcd99cf6ae73fbec3a9b", track: "Violet Stars Happy Hunting!!!", artist: "Janelle Monae", album: "Metropolis The Chase Suite", duration: 193.617, trackNumber: 2, albumArtist: "" } sandbox.js:305
"LFM.track.updateNowPlaying - response:" Object { error: 6, message: "duration is not a valid integer: 19…", links: Array[0] }

**Comment by fuzeman** [comment] 2015-05-19 23:37
@lucasoutloud ah, "duration" is being sent to last.fm as a float (not an integer), not sure why I haven't seen this from my testing...

Will start working on a fix now.

**Comment by fuzeman** [comment] 2015-05-19 23:56
**[v0.8.4-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.4-beta)** has been released

**Comment by lucasoutloud** [comment] 2015-05-20 00:09
@fuzeman This latest release fixed the issue. Thanks so much for all your hard work!!

**Comment by fuzeman** [comment] 2015-06-03 09:20
I've noticed some issues with scrobbling today, will start working on a fix later tonight.

**Comment by fuzeman** [comment] 2015-06-03 13:04
Scrobbling fix released in **[v0.8.5-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.5-beta)**

**Comment by PerfectSlayer** [comment] 2015-06-03 15:57
Thanks for the update! Will try it tonight :wink:

**Comment by lucasoutloud** [comment] 2015-06-05 17:59
There seems to be a new bug with the latest beta, but I'm not sure what's causing it to not scrobble. Here's some logs:
"GMS-PS" Object { oz: false, Rw: Array[2], gq: Object, HAa: Object, H1: null, CC: Object, ad: Object, xc: Object, ny: null, cH: Object, 1 more… } Array [ Object, false, false, Object ] page.js:57:16
"GMS.Scrobbler.setPlaying" null sandbox.js:305
"GMS.Scrobbler.setPlayingState" true sandbox.js:305
"Entry exists, skipping creation and adding a timestamp" main.js:339
GET 
https://ssl.google-analytics.com/__utm.gif [HTTP/2.0 200 OK 356ms]
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] __utm.gif
"Entry exists, skipping creation and adding a timestamp"

**Comment by fuzeman** [comment] 2015-06-10 05:07
Looks like a change to Google Music has caused scrobbling to stop again..

Will start working on a fix for this issue tonight.

**Comment by fuzeman** [comment] 2015-06-10 08:05
Fix for the latest scrobbling issue released in **[v0.8.6-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6-beta)**

**Comment by PerfectSlayer** [comment] 2015-06-10 17:12
Thanks! :+1:

**Comment by mrgar** [comment] 2015-06-14 13:39
Sadly mine still doesn't work. Would someone direct me what kind of logs would be helpful to resolve the issue with scrobbling?

**Comment by cjbrambo** [comment] 2015-06-14 19:08
Installed this add-on and refreshed, my library suddenly disappeared. Ran gmusicapi script from a box, music is still there, just not showing in browser. Removed this add-on and refreshed, library reappeared. 

ff-38.0.5

**Comment by fuzeman** [comment] 2015-06-15 00:28
Could you retrieve the addon logs by doing the following:
 - Open ```about:config```, set ```extensions.jid1-rbAJu4BHjMqTww@jetpack.sdk.console.logLevel``` to ```debug``` *(create a new preference)*
 - Open the Browser Console (```Ctrl + Shift + J``` or ```Menu -> Developer -> Browser Console```)
 - Open/Refresh Google Music *(@mrgar: start playing a song)*
 - Copy the entries displayed in the browser console

**Comment by mrgar** [comment] 2015-06-18 17:04
Here's the output from my browser

"GMS-PS" Object { wy: false, dw: Array[2], Jp: Object, xya: Object, Z_: null, HB: Object, Sc: Object, tc: Object, zx: null, fG: Object, 1 more… } Array [ Object, true, false, Object ] page.js:57:16
"GMS-PS" Object { wy: false, dw: undefined, Jp: Object, xya: Object, Z_: null, D: Object, cj: Object, I: Object, Fcb: Object, Qva: Object, 43 more… } Array [ Object, true, false, Object ] page.js:57:16
"GMS-PS - Called with "player" in an invalid state" page.js:70:20
"GMS.Scrobbler.setPlaying" Object { track: "Washing My Hands", artist: "Karl O'Connor & Peter Sutton", album: "Againstnature", duration: 152, trackNumber: 1 } sandbox.js:305
"GMS.Scrobbler.setPlayingState" true

**Comment by fuzeman** [comment] 2015-06-19 05:05
@mrgar Looks like your last.fm account might not be authorized, what does it show in:
```
Settings (in Google Music) -> Google Music Scrobbler
```

You could also try un-linking and then linking your account again. Check the browser console again for any errors in the linking process.

-------------------------

It should look something like:

![](https://i.imgur.com/v9BeAmY.png)

**Comment by mrgar** [comment] 2015-06-19 16:23
@fuzeman 

I followed your advice and it works now. Many thanks. However I didn't get confirm link or something like that before Iceweasel was upgraded earlier, unless i missed it.

**Comment by wesQ3** [comment] 2015-07-04 21:45
0.8.6 is working fine here, Firefox 40 beta. Should this issue be closed now?

**Comment by fuzeman** [comment] 2015-07-06 08:50
Yeah, new issues can be created for any future problems.

**Closed by fuzeman** 2015-07-06 08:50 UTC
Labels: 2 - In Progress, bug
